# Generated by Django 5.0.7 on 2024-09-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_customer_reservation_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='viptable',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.vipreservation'),
        ),
    ]
