# Generated by Django 5.0.7 on 2024-09-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_viptable_reservation_vipcustomer_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vipcustomer',
            name='reservation',
        ),
    ]
