# Generated by Django 5.0.7 on 2024-09-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_vipcustomer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipreservation',
            name='vip_customer',
            field=models.CharField(max_length=100),
        ),
    ]
