# Generated by Django 5.0.7 on 2024-09-14 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_vipreservation_vip_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='vipcustomer',
            name='vip_table',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='mainapp.table'),
        ),
        migrations.AlterField(
            model_name='vipreservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_reservations', to='mainapp.viptable'),
        ),
        migrations.AlterField(
            model_name='vipreservation',
            name='vip_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_reservations', to='mainapp.vipcustomer'),
        ),
    ]
